### ISSUE TITLE
"Report an issue" doesn't work within VSCode

### ISSUE THREAD

**Issue by derek1ee** [confluentinc/vscode#295]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### On what operating system are you seeing the problem?

macOS (Apple/arm64)

### VS Code version

Version: 1.93.1 (Universal)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 22.6.0

### Version of Confluent extension

v0.16.3

### To Reproduce

1. Open the "Confluent" tab from left nav
2. Under "Support", select "Report an issue"
3. Fill in details, make sure all required fields are complete
4. Click "Create on GitHub"

### Current vs. Expected behavior

Expect: Able to create an issue on github

Actual: No response upon clicking the button

### Which area(s) are affected? (Select all that apply)

Installation

**Comment by jlrobins** [comment]
Hi Derek,

The 'Report an issue' functionality makes use of [common infrastructure internal to VS Code](https://code.visualstudio.com/api/get-started/wrapping-up#issue-reporting). When you hit the 'Preview on GithHub,' submit button on the the form, it hands off to your system's web browser with a URL to GitHub that prefills out GitHub's issue reporter form, for you to then refine and submit. Apologies that it did not work for you that time. Could the browser window perhaps have been obscured or perhaps blocked at the GitHub login flow? It does look from your other reports that it has worked for you in the past, and also it appears that it was used to report this issue (given the system and A/B test details it provides). Could you perhaps try again and confirm? Thanks!

I just used it to create https://github.com/confluentinc/vscode/issues/297, and it worked as expected.

**Comment by shouples** [comment]
@derek1ee one more suggestion: when you have the Issue Reporter window open, try to open the dev tools pane (`F12`) before trying to submit an issue; there may be some silent network errors happening:
<img width="1347" alt="image" src="https://github.com/user-attachments/assets/cc88dc8e-41c9-421c-805d-8a958ad40c4b">

**Comment by derek1ee** [comment]
I was not able to open the dev tool panel?

Just tried this again, it looks like the issue only repros when "Confluent" extension is selected, if I change it to "C#" for example, a browser tab is successfully opened and an issue created.

Do we have some additional validation maybe that blocks issue creation from vsode?

**Comment by jlrobins** [comment]
@derek1ee  Are you trying to file an issue from a non-Confluent-firewall-active machine yet from a github account linked to your Confluent account? That won't work due to ConfluentInc's organization settings vs the half-open vscode repo (and not due to anything in the extension itself). If you either:
  * Be logged into GitHub on a non-confluent-firewall computer using a GitHub account that is unafilliated with ConfluentInc,
  * Be logged into your ConfluentInc GitHub account but use the issue reporting functionality from behind Confluent firewall.
  
 Then it really should work and has been tested both ways.
 
 Does this help?

**Comment by shouples** [comment]
> I was not able to open the dev tool panel?

@derek1ee it looks like this may be controlled by [a new Issue Reporter setting released in 1.93](https://code.visualstudio.com/updates/v1_93#_new-issue-reporter-implementation):
<img width="637" alt="image" src="https://github.com/user-attachments/assets/fd2943d4-3b65-414f-a205-615d9c50c8f7">

Try this:
- go into your settings (`Cmd+,`)
- filter `@id:issueReporter.experimental.auxWindow`
- uncheck/disable that "Aux Window" setting
- reopen the Issue Reporter

`F12` (or `fn+F12`, depending on keyboard settings) should now surface the dev tools panel.

Let me know if this helps at all!

**Comment by derek1ee** [comment]
@shouples turning the experimental feature off allowed me to open F12 to see network traffic. Looks like the POST call failed 403 Forbidden:

{
  "message": "Resource protected by organization SAML enforcement. You must grant your OAuth token access to this organization.",
  "documentation_url": "https://docs.github.com/articles/authenticating-to-a-github-organization-with-saml-single-sign-on/",
  "status": "403"
}

**Comment by shouples** [comment]
@derek1ee that helps, thanks! Do you see any indicators in the Accounts section prompting for additional GitHub sign-in or anything?
<img width="317" alt="image" src="https://github.com/user-attachments/assets/6b53a0a7-1ab0-433c-ba84-b0fc6cf9c6da">

**Comment by derek1ee** [comment]
@shouples Doesn't appear to be, see screenshot below. I will send you the network trace offline.

<img width="635" alt="Screenshot 2024-09-27 at 9 48 01 AM" src="https://github.com/user-attachments/assets/bffb9dff-f24c-40f1-be94-37effc92ebe5">

**Comment by shouples** [comment]
Thanks again for your patience on this one @derek1ee -- I'm going to go ahead and close this since it isn't specifically related to our extension.

For anyone else that encounters this behavior, this seems to be related to how VS Code handles SAML sessions when the user is part of a GitHub organization that requires SAML/SSO.

Within VS Code, a basic authentication with GitHub (like for settings sync) only requires the `email` scope, but other extensions (like [GitHub Pull Requests](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github)) will require more, that may prompt users to reauthenticate and/or show users this kind of GitHub page from their default browser:

![image](https://github.com/user-attachments/assets/61b62157-208a-42b4-b867-20940c62f9dd)

Once the user clicks "Authorize" for their given organization, the Issue Reporter functionality should work as expected and stop returning 403 errors.
