### ISSUE TITLE
Suggestion: Remove  {topicName} -" prefix from schema key/value tree item

### ISSUE THREAD

**Issue by derek1ee** [confluentinc/vscode#296]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### On what operating system are you seeing the problem?

macOS (Apple/arm64)

### VS Code version

Version: 1.93.1 (Universal)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 22.6.0

### Version of Confluent extension

v0.16.3

### To Reproduce

1. Install, signin to CC, and navigate to a topic with schema(s).
2. Expand the chevron of said topic
3. Observe child tree items

### Current vs. Expected behavior

Expected: See two child items, "key" and "value"
Actual: See two child items, "{topicName} - key" and "{topicName} - value" 

Since the topic name is immediately available on the parent node, the extra duplication here make it more difficult to read and navigate, suggest remove topic name as prefix.

<img width="333" alt="Screenshot 2024-09-24 at 4 54 50 PM" src="https://github.com/user-attachments/assets/28377353-5cd0-4a07-b797-3f808c33fce0">

### Which area(s) are affected? (Select all that apply)

Schemas

**Comment by shouples** [comment]
Hey @derek1ee -- this is not a bug, but intended behavior since we group schema _subjects_ associated with topics based on the [TopicNameStrategy](https://docs.confluent.io/platform/current/schema-registry/fundamentals/serdes-develop/index.html#overview), similar to CCloud.

Under each subject item will be all versions of the schema, in descending order:
<img width="436" alt="image" src="https://github.com/user-attachments/assets/962d7302-c47a-4920-ac49-d6609eb70be3">

We're also pulling these `{topic}-key`/`{topic}-value` subject values directly from the Schema Registry REST proxy, so attempting to alter them could result in confusion for developers working with those schemas. In the future, if we start supporting more than the `TopicNameStrategy`, we may be able to adjust the hierarchy and labeling here, but that will require some coordination with the Schema Registry API and CCloud developers.
