### ISSUE TITLE
Extension not supported on VS Code for the Web

### ISSUE THREAD

**Issue by derek1ee** [confluentinc/vscode#509]
1. Go to https://vscode.dev/
2. Go to extension tab, search for Confluent and try to install.
3. Observe that it's not supported.

<img width="878" alt="Screenshot 2024-11-01 at 1 07 12 PM" src="https://github.com/user-attachments/assets/94d2844a-e5bc-4543-ad1b-8dd1c2c08494">

**Comment by shouples** [comment]
Closing as not-planned since we'll need to discuss this one across the extension and sidecar teams; the main blocker is the fact that the sidecar native executable can't run in the web environment, but we would also have to curate current and future roadmap functionality for web-extension compatibility. None of the [configurations](https://code.visualstudio.com/api/extension-guides/web-extensions) to make it web-compatible are set, and we also don't export the `web` target in any of our packaging+publishing flows.

Codespaces may be more of an easier win, but the pure web experience is out of scope for the time being.
