### ISSUE TITLE
Start local should check kafka & SR by default

### ISSUE THREAD

**Issue by derek1ee** [confluentinc/vscode#673]
Currently, when click on the start button to start local environment, nothing is checked.

I think we should by default check both Kafka & SR.

**Comment by shouples** [comment]
Setting as a bug since we're trying to set Kafka by default but it isn't affecting anything since we aren't using the `showQuickPick()` API
<img width="771" alt="image" src="https://github.com/user-attachments/assets/8fbc338a-1683-4bda-9ee6-75afec146709">
https://github.com/confluentinc/vscode/blob/f32697965c90506c92fb4cbe51c4d0234ad9133b/src/quickpicks/localResources.ts#L22-L36

**Comment by shouples** [comment]
@derek1ee Kafka is now automatically checked by default (when it isn't running) during the "Start Local Resources" action as of https://github.com/confluentinc/vscode/pull/713, but we're still leaving SR unchecked for now.
